# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
    "name": "Amazon",
    "symbol": "AMZN",
    "price": "127.00",
    "image": "amz.png"
}
###
@assetId = {{createAsset.response.body._id}}

###
GET http://localhost:3000/assets

###
GET http://localhost:3000/assets/AMZN

###
# @name createWallet
POST http://localhost:3000/wallets
Content-Type: application/json

###
@walletId = {{createWallet.response.body._id}}

###
GET http://localhost:3000/wallets

###
GET http://localhost:3000/wallets/d1d1d6bb-6d0f-403e-b006-d227090265ac


###
POST http://localhost:3000/wallets/{{walletId}}/assets
Content-Type: application/json

{
    "assetId": "{{assetId}}",
    "shares": 127.00
}

###
# @name createOrder
POST http://localhost:3000/orders
Content-Type: application/json

{
    "walletId": "{{walletId}}",
    "assetId": "{{assetId}}",
    "shares": 10,
    "price": 100,
    "type": "BUY"
}

###
@orderId = {{createOrder.response.body._id}}


###
GET http://localhost:3000/orders

###
GET http://localhost:3000/orders?walletId={{walletId}}

###
GET http://localhost:3000/orders/{{orderId}}